<?php

namespace OC\PlatformBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function getArticleBySlug($slug) {
        return $this->find($slug);
    }

    public function getArticleById($id) {
        return $this->find($id);
    }

    public function getAllArticles() {
        return $this->findAll();
    }

    public function getArrayAllArticles() {
        
    }

}
